name: copr-build

on:
  push:
    branches:
      - master

jobs:
  copr_build:
    name: Create copr build
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'oamg'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/heads/master"

      - name: Install copr-cli
        id: install-copr-cli
        run: pip install copr-cli

      - name: Trigger fedora copr build
        id: trigger_fedora_build
        env:
          COPR_CONFIG: "copr_fedora.conf"
          COPR_CHROOT: "epel-7-x86_64,epel-8-x86_64"
        run: |
          cat << EOF > $COPR_CONFIG
          [copr-cli]
          login = ${{ secrets.FEDORA_COPR_LOGIN }}
          username = @oamg
          token = ${{ secrets.FEDORA_COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

          make copr_build

      - name: Trigger internal copr build
        id: trigger_internal_build
        env:
          COPR_CONFIG: "copr_internal.conf"
        run: |
          cat << EOF > $COPR_CONFIG
          [copr-cli]
          login = ${{ secrets.INTERNAL_COPR_LOGIN }}
          username = oam-group
          token = ${{ secrets.INTERNAL_COPR_TOKEN }}
          copr_url = ${{ secrets.INTERNAL_COPR_URL }}
          EOF

          make copr_build
